name: Update Store Info
on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  update-store-info:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Install shopware-cli
        uses: shopware/shopware-cli-action@v3
      - name: Build
        shell: bash
        run: shopware-cli account producer extension info push .
        env:
          SHOPWARE_CLI_ACCOUNT_CLIENT_ID: ${{ secrets.SHOPWARE_CLI_ACCOUNT_CLIENT_ID }}
          SHOPWARE_CLI_ACCOUNT_CLIENT_SECRET: ${{ secrets.SHOPWARE_CLI_ACCOUNT_CLIENT_SECRET }}
